nginx:
    container_name: nginx-virtual-hosts
    build: .
    ports:
        - 8080:80
        - 4443:443
    volumes:
        - ./www/:/var/www/:ro
        - ./sites-enabled/:/etc/nginx/sites-enabled/
